// Generated by `npm run images:pull`.
// Keep this empty fallback committed so the app still builds before the one-time image pull.

export interface CarImageRecord {
  src: string;
  carImagesUrl: string;
  sourcePageUrl: string;
  creatorName: string;
  creatorUrl?: string;
  creditText: string;
  licenseCode: string;
  licenseName: string;
  licenseUrl: string;
  attributionRequired: boolean;
  photoId: string;
}

export const CAR_IMAGE_MANIFEST: Record<string, CarImageRecord> = {};
